version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/App"
    schedule:
      # Check for updates to nuget every week
      interval: "weekly"
