name: Release PROD

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9].[0-9].[0-9]"
      - "[0-9].[0-9].[0-9]-PRE"

jobs:
  docker:
    name: docker pull, tag and push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker login to ACR
        uses: docker/login-action@v2
        with:
          registry: anderstest.azurecr.io
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      # Set semantic tag variable
      - name: Set semantic tag variable
        if: ${{ github.ref_type == 'tag' }}
        run: |
          echo "SEM_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "GIT_SHA=$(git rev-parse --short $GITHUB.SHA)" >> $GITHUB_ENV

      # Docker pull, tag & push
      - name: Docker pull, tag & push
        if: ${{ github.ref_type == 'tag' }}
        env:
          DOCKER_IMAGE: anderstest.azurecr.io/dotnet-github-actions-test
        run: |
          docker pull $DOCKER_IMAGE:latest
          docker image tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:$SEM_TAG
          docker image push $DOCKER_IMAGE:$SEM_TAG